ARG FPC_BASIC_IMAGE_NAME
FROM $FPC_BASIC_IMAGE_NAME 
ARG FREE_PASCAL_COMPILER_SOURCE
ARG FREE_PASCAL_COMPILER_BRANCH
ENV WORKDIR=$SCRIPT_INSTALL_PATH
ENV FREE_PASCAL_COMPILER_SOURCE_DIR $WORKDIR/freepascal
ENV FPC_VERSION_FOR_BUILD="latest"
RUN echo $FREE_PASCAL_COMPILER_BRANCH $FREE_PASCAL_COMPILER_SOURCE
RUN git clone --single-branch --branch $FREE_PASCAL_COMPILER_BRANCH $FREE_PASCAL_COMPILER_SOURCE $FREE_PASCAL_COMPILER_SOURCE_DIR
RUN cd $FREE_PASCAL_COMPILER_SOURCE_DIR&&git pull
# build fpc for x86-64 linux
RUN cd $FREE_PASCAL_COMPILER_SOURCE_DIR&& make distclean install INSTALL_PREFIX=$FPC_INSTALL_PREFIX
#"OPT=-Oodfa"  FPC_VERSION=$FPC_VERSION_FOR_BUILD
RUN ls $FPC_DIR -a
ENV COMPILER_NAME $FPC_INSTALL_PREFIX/$FPC_VERSION_FOR_BUILD/lib/fpc
#linux compiler check
RUN $COMPILER_NAME -h
